package com.qaprosoft.zafira.constant;

public class JSONConstant {
    public static final String ID_KEY = "id";
    public static final String ACCESS_TOKEN_KEY = "accessToken";
    public static final String TYPE_RS_KEY = "type";
    public static final String QUEUE_ITEM_URL_KEY = "queueItemUrl";
    public static final String WORK_ITEM_RS_KEY = "workItem";
    public static final String STATUS_KEY = "status";
    public static final String ARTIFACT_ID_KEY = "artifacts[0].id";
    public static final String JIRA_ID_KEY = "jiraId";
    public static final String ALL_ID_FROM_RESULTS_KEY = "results[0].id";
    public static final String CI_RUN_ID_KEY = "ciRunId";
    public static final String INTEGRATION_ENABLED_KEY = "enabled";
    public static final String INTEGRATION_CONNECTED_KEY = "connected";
    public static final String WORK_ITEM_ID_CHECK_KEY = "results[0].workItems[0].id";
    public static final String WORK_ITEMS_ARRAY_KEY = "results[0].workItems";
    public static final String ALL_TEST_RUN_ID_BY_SEARCH_CRITERIA_KEY = "results.id";
    public static final String JIRA_INTEGRATION_ID_KEY = "TEST_CASE_MANAGEMENT.JIRA[0].integrationId";
    public static final String TESTRAIL_INTEGRATION_ID_KEY = "TEST_CASE_MANAGEMENT.TESTRAIL[0].integrationId";
    public static final String QTEST_INTEGRATION_ID_KEY = "TEST_CASE_MANAGEMENT.QTEST[0].integrationId";
    public static final String ZEBRUNNER_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.ZEBRUNNER[0].integrationId";
    public static final String SELENIUM_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.SELENIUM[0].integrationId";
    public static final String BROWSERSTACK_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.BROWSERSTACK[0].integrationId";
    public static final String MCLOUD_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.MCLOUD[0].integrationId";
    public static final String SAUCELABS_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.SAUCELABS[0].integrationId";
    public static final String LAMBDATEST_INTEGRATION_ID_KEY = "TEST_AUTOMATION_TOOL.LAMBDATEST[0].integrationId";
    public static final String AMAZON_INTEGRATION_ID_KEY = "STORAGE_PROVIDER.AMAZON[0].integrationId";
    public static final String SLACK_INTEGRATION_ID_KEY = "SLACK.SLACK[0].integrationId";
    public static final String RABBITMQ_INTEGRATION_ID_KEY = "MESSAGE_BROKER.RABBITMQ[0].integrationId";
    public static final String EMAIL_INTEGRATION_ID_KEY = "MAIL.EMAIL[0].integrationId";
    public static final String INVITES_TOKEN_KEY = "[0].token";
    public static final String LAST_NAME_KEY = "lastName";
    public static final String PERMISSIONS_IDS_KEY = "permissions.id";
    public static final String IMAGE_URL_KEY = "url";
    public static final String USERS_IDS_KEY = "users.id";
    public static final String FILTER_NAME_KEY = "name";
    public static final String DASHBOARD_TITLE_KEY = "title";
    public static final String USERS_KEY = "users";
}
